agent:
  agent_config:
    complete_step: 3000000
    max_steps: 128
  agent_name: AtariImpalaOpt
  agent_num: 1
alg:
  alg_config:
    BATCH_SIZE: 512
    agent_num: 1
    api_type: standalone
    env_attr:
      agent_ids: &id001
      - 0
      api_type: standalone
      episode_limit: 300
      n_actions: 7
      n_agents: 2
      obs_shape: 17
      state_shape: 27
    instance_num: 80
    prepare_times_per_train: 1
    train_per_checkpoint: 1
  alg_name: IMPALAOpt
  model_info:
    actor:
      action_dim: 4
      input_dtype: uint8
      model_config:
        LR: 0.0005
        action_type: null
        agent_ids: *id001
        api_type: standalone
        episode_limit: 300
        grad_norm_clip: 40.0
        n_actions: 7
        n_agents: 2
        obs_shape: 17
        sample_batch_step: 128
        state_shape: 27
      model_name: ImpalaCnnOpt
      state_dim:
      - 84
      - 84
      - 4
      state_mean: 0.0
      state_std: 255.0
      type: learner
archive_root: ./logs_test_st
bm_board: null
bm_eval: {}
bm_id: impala_origin_core80
config_yaml: /home/xys/xingtian-test/xingtian-project-pipeline_impala/logs_test_st/impala_origin_core80+230905163108T0/benchmark/train_config.yaml
end_time: 2023-09-05 16:31:08.486196
env:
  env_info:
    name: BreakoutNoFrameskip-v4
    vector_env_size: 1
    vision: false
  env_name: VectorAtariEnv
eval_gap: 200
record_csv: /home/xys/xingtian-test/xingtian-project-pipeline_impala/logs_test_st/impala_origin_core80+230905163108T0/benchmark/records.csv
start_time: 2023-09-05 16:31:08.395952
workspace: /home/xys/xingtian-test/xingtian-project-pipeline_impala/logs_test_st/impala_origin_core80+230905163108T0/benchmark
